blank_issues_enabled: true
contact_links:
  - name: Ask questions
    url: https://github.com/Explaimaus-Hash/GitHub-clone-/discussions
    about: Please ask questions in Discussions.
  - name: Make a proposal
    url: https://github.com/Explaimaus-Hash/GitHub-clone-/discussions/categories/proposal
    about: Please make proposals in Discussions.
